// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: fees.proto

package fees

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FeesClient is the client API for Fees service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FeesClient interface {
	ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error)
}

type feesClient struct {
	cc grpc.ClientConnInterface
}

func NewFeesClient(cc grpc.ClientConnInterface) FeesClient {
	return &feesClient{cc}
}

func (c *feesClient) ListFees(ctx context.Context, in *ListFeesRequest, opts ...grpc.CallOption) (*ListFeesResponse, error) {
	out := new(ListFeesResponse)
	err := c.cc.Invoke(ctx, "/Fees/ListFees", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeesServer is the server API for Fees service.
// All implementations must embed UnimplementedFeesServer
// for forward compatibility
type FeesServer interface {
	ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error)
	mustEmbedUnimplementedFeesServer()
}

// UnimplementedFeesServer must be embedded to have forward compatible implementations.
type UnimplementedFeesServer struct {
}

func (UnimplementedFeesServer) ListFees(context.Context, *ListFeesRequest) (*ListFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFees not implemented")
}
func (UnimplementedFeesServer) mustEmbedUnimplementedFeesServer() {}

// UnsafeFeesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FeesServer will
// result in compilation errors.
type UnsafeFeesServer interface {
	mustEmbedUnimplementedFeesServer()
}

func RegisterFeesServer(s grpc.ServiceRegistrar, srv FeesServer) {
	s.RegisterService(&Fees_ServiceDesc, srv)
}

func _Fees_ListFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFeesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeesServer).ListFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Fees/ListFees",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeesServer).ListFees(ctx, req.(*ListFeesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Fees_ServiceDesc is the grpc.ServiceDesc for Fees service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Fees_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Fees",
	HandlerType: (*FeesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFees",
			Handler:    _Fees_ListFees_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fees.proto",
}
